export enum PersonType {
  Chase = "Chase",
  Lien = "Lien",
  Taylor = "Taylor",
  Saskia = "Saskia",
  Kushla = "Kushla",
  Patrick = "Patrick",
}

export enum ItineraryType {
  Flight = "Flight",
  CheckIn = "CheckIn",
  CheckOut = "CheckOut",
  Drive = "Drive",
  Walk = "Walk",
  Bus = "Bus",
  Train = "Train",
  Activity = "Activity",
  Sleep = "Sleep",
  Food = "Food",
}

export interface Itinerary {
  title: string;
  type: ItineraryType;
  fixedStart?: number; // Will either be the start or the duration, starts is as 24hr time, e.g. 1430 for 2:30pm
  fixedDuration?: number; // Duration in minutes
  recommendedDuration?: number; // Duration in minutes
  attendees: PersonType[];
  day?: number;
  link?: string;
}

export const START_DAY = new Date(2024, 7, 29);

const ITINERARY: Itinerary[] = [
  {
    // TODO
    title: "Flight to Lisbon",
    type: ItineraryType.Flight,
    fixedStart: 1600,
    fixedDuration: 120,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "",
  },
  {
    // TODO
    title: "Taxi to Hotel",
    type: ItineraryType.Drive,
    fixedDuration: 30,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "",
  },
  {
    // TODO
    title: "Check In to Hotel",
    type: ItineraryType.CheckIn,
    fixedDuration: 30,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "",
  },
  {
    // TODO
    title: "Relax at Hotel",
    type: ItineraryType.Activity,
    recommendedDuration: 60,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "",
  },
  {
    // TODO
    title: "Walk to Restaurant",
    type: ItineraryType.Walk,
    fixedDuration: 15,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "",
  },
  {
    // TODO
    title: "Dinner at De Terra",
    type: ItineraryType.Food,
    fixedStart: 2100,
    recommendedDuration: 120,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "",
  },
  {
    // TODO
    title: "Walk to Hotel",
    type: ItineraryType.Walk,
    fixedDuration: 15,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "",
  },
  {
    title: "Sleep",
    type: ItineraryType.Sleep,
    recommendedDuration: 60 * 10,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "",
  },
  // TODO
  {
    title: "Breakfast at Hotel",
    type: ItineraryType.Food,
    fixedStart: 900,
    recommendedDuration: 90,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "",
  },
  {
    title: "MEOW (5 hours)",
    type: ItineraryType.Activity,
    recommendedDuration: 60 * 5,
    attendees: [PersonType.Chase, PersonType.Lien],
  },
  {
    title: "Taxi to festival",
    type: ItineraryType.Drive,
    fixedDuration: 30,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "https://maps.app.goo.gl/uE8A7yqejchAzXu78",
  },
  {
    title: "Lisboa Festival",
    type: ItineraryType.Activity,
    fixedStart: 1600,
    fixedDuration: 8 * 60,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "https://meokalorama.pt/en",
  },
  {
    title: "Flight to Lisbon",
    type: ItineraryType.Flight,
    fixedStart: 1510,
    fixedDuration: 2 * 60 + 50,
    attendees: [PersonType.Kushla, PersonType.Saskia, PersonType.Taylor],
  },
  {
    title: "Travel to Cascais",
    type: ItineraryType.Bus,
    fixedStart: 1800,
    fixedDuration: 120,
    attendees: [PersonType.Kushla, PersonType.Saskia, PersonType.Taylor],
    link: "https://maps.app.goo.gl/1rT7sb7zG3VqcYcv5",
  },
  {
    title: "Check into Cascias Hotel",
    type: ItineraryType.CheckIn,
    fixedStart: 2000,
    fixedDuration: 30,
    attendees: [PersonType.Kushla, PersonType.Saskia, PersonType.Taylor],
    link: "https://www.vilabicuda.com/en/",
  },
  {
    title: "Rest at hotel",
    type: ItineraryType.Activity,
    recommendedDuration: 30,
    attendees: [PersonType.Kushla, PersonType.Saskia, PersonType.Taylor],
    link: "https://www.vilabicuda.com/en/",
  },
  {
    title: "Dinner at Glass Terrace",
    type: ItineraryType.Food,
    fixedStart: 2100,
    recommendedDuration: 120,
    attendees: [PersonType.Taylor, PersonType.Saskia, PersonType.Kushla],
    link: "https://maps.app.goo.gl/GgZ8oRG5WXcUxAtd7",
  },
  {
    title: "Sleep",
    type: ItineraryType.Sleep,
    recommendedDuration: 60 * 10,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
  },
  {
    title: "Travel to Cascais",
    type: ItineraryType.Bus,
    fixedStart: 900,
    fixedDuration: 90,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "https://maps.app.goo.gl/1rT7sb7zG3VqcYcv5",
  },
  {
    title: "Rest at hotel",
    type: ItineraryType.Activity,
    recommendedDuration: 30,
    attendees: [PersonType.Chase, PersonType.Lien],
    link: "https://www.vilabicuda.com/en/",
  },
  {
    title: "Walk to Carmo",
    type: ItineraryType.Walk,
    fixedDuration: 20,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://maps.app.goo.gl/1rT7sb7zG3VqcYcv5",
  },
  {
    title: "Brunch at Carmo",
    type: ItineraryType.Food,
    fixedStart: 1130,
    recommendedDuration: 90,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://maps.app.goo.gl/1rT7sb7zG3VqcYcv5",
  },
  {
    title: "Explore Cascais",
    type: ItineraryType.Activity,
    recommendedDuration: 60 * 3,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://www.tripadvisor.co.uk/Attractions-g189154-Activities-c47-t76-Cascais_Lisbon_District_Central_Portugal.html",
  },
  {
    title: "Surf Lessons with Taylor",
    type: ItineraryType.Activity,
    recommendedDuration: 60 * 4,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
  },
  {
    title: "Rest at hotel",
    type: ItineraryType.Activity,
    recommendedDuration: 60 * 2,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://www.vilabicuda.com/en/",
  },
  {
    title: "Dinner at Baía do Peixe",
    type: ItineraryType.Food,
    fixedStart: 1930,
    recommendedDuration: 60 * 2,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://maps.app.goo.gl/p3CZ1LUdj333jJsP8",
  },
  {
    title: "Sleep",
    type: ItineraryType.Sleep,
    recommendedDuration: 60 * 10,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
  },
  {
    title: "Breakfast at Euphoria",
    type: ItineraryType.Food,
    fixedStart: 1000,
    recommendedDuration: 90,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://maps.app.goo.gl/FrXpwE1nBP5tMhuMA",
  },
  {
    title: "9 holes of golf",
    type: ItineraryType.Activity,
    recommendedDuration: 60 * 4,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://www.quintadamarinha.com/en/menu/golf/golf-courses-cascais-portugal.aspx",
  },
  {
    title: "Lunch at A Nova Estrela",
    type: ItineraryType.Food,
    recommendedDuration: 60 * 2,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://maps.app.goo.gl/SCz2fdzvCQCFL7s99",
  },
  {
    title: "Relax on Praia da Conceição beach",
    type: ItineraryType.Activity,
    recommendedDuration: 60 * 3,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://maps.app.goo.gl/Qa2vDMXWYzoptvYc7",
  },
  {
    title: "Rest at hotel",
    type: ItineraryType.Activity,
    recommendedDuration: 60 * 2,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://www.vilabicuda.com/en/",
  },
  {
    title: "Dinner at Mar do Inferno",
    type: ItineraryType.Food,
    recommendedDuration: 60 * 2,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
    ],
    link: "https://maps.app.goo.gl/gkeknupWhoWBDKid9",
  },
  {
    title: "Flight to Lisbon",
    type: ItineraryType.Flight,
    fixedStart: 1900,
    fixedDuration: 2 * 60 + 50,
    attendees: [PersonType.Patrick],
  },
  {
    title: "Travel to Cascais",
    type: ItineraryType.Bus,
    fixedDuration: 60 * 2.5,
    attendees: [PersonType.Patrick],
    link: "https://maps.app.goo.gl/1rT7sb7zG3VqcYcv5",
  },
  {
    title: "Sleep",
    type: ItineraryType.Sleep,
    recommendedDuration: 60 * 10,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
  },
  {
    title: "Breakfast at LOCAL",
    type: ItineraryType.Food,
    fixedStart: 1000,
    recommendedDuration: 90,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
    link: "https://maps.app.goo.gl/GTsR13jNumcgCyB37",
  },
  {
    title: "Rent Car",
    type: ItineraryType.Drive,
    recommendedDuration: 60,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
  },
  {
    title: "Drive to Sintra",
    type: ItineraryType.Drive,
    fixedDuration: 60,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
    link: "https://maps.app.goo.gl/3ucA2FE8nm3YkNXb6",
  },
  {
    title: "Explore Palace of Pena",
    type: ItineraryType.Activity,
    recommendedDuration: 60 * 3,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
    link: "https://www.parquesdesintra.pt/en/parks-monuments/park-and-national-palace-of-pena/",
  },
  {
    title: "Lunch at Casa das Minas",
    type: ItineraryType.Food,
    recommendedDuration: 60 * 2,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
    link: "https://maps.app.goo.gl/rV18mNjGchBM78co6",
  },
  {
    title: "Explore Sintra Town",
    type: ItineraryType.Activity,
    recommendedDuration: 60 * 2,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
    link: "https://www.tripadvisor.co.uk/Attractions-g189164-Activities-Sintra_Sintra_Municipality_Lisbon_District_Central_Portugal.html",
  },
  {
    title: "Drive back to hotel",
    type: ItineraryType.Drive,
    fixedDuration: 60,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
    link: "https://maps.app.goo.gl/1rT7sb7zG3VqcYcv5",
  },
  {
    title: "Rest at hotel",
    type: ItineraryType.Activity,
    recommendedDuration: 60 * 2,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
    link: "https://www.vilabicuda.com/en/",
  },
  {
    title: "Dinner at Spi",
    type: ItineraryType.Food,
    recommendedDuration: 60 * 2,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
    link: "https://maps.app.goo.gl/GjsLHU8C1eJHY6adA",
  },
  {
    title: "Sleep",
    type: ItineraryType.Sleep,
    recommendedDuration: 60 * 10,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
  },
  {
    title: "Check out of hotel",
    type: ItineraryType.CheckOut,
    fixedStart: 900,
    fixedDuration: 100,
    attendees: [
      PersonType.Chase,
      PersonType.Lien,
      PersonType.Taylor,
      PersonType.Saskia,
      PersonType.Kushla,
      PersonType.Patrick,
    ],
  },
];

export default ITINERARY;
